server {
    listen 80;
    listen [::]:80;
    server_name bettercalories.app www.bettercalories.app;

    root /var/www/bettercalories.app/html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        return 301 https://bettercalories.app$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.bettercalories.app;

    ssl_certificate /etc/letsencrypt/live/bettercalories.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bettercalories.app/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    location / {
        return 301 https://bettercalories.app$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name bettercalories.app;

    root /var/www/bettercalories.app/html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/bettercalories.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bettercalories.app/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
